[package]
name = "lazers_hyper_client"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

build = "tango-build.rs"

[dependencies]
hyper = "*"
url = "*"

[dependencies.lazers-traits]
path = "../lazers-traits"

[build-dependencies]
tango = "0.5.0"

[lib]
name = "lazers_hyper_client"
