[package]
name = "lazers-replicator"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

build = "tango-build.rs"

[dependencies]
hyper = "*"

[dependencies.lazers-db]
path = "../lazers-db"

[dependencies.lazers-changes-stream]
path = "../lazers-changes-stream"

[build-dependencies]
tango = "0.5.0"

[lib]
name = "lazers_replicator"
