[package]
name = "lazers-traits"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

build = "tango-build.rs"

[dependencies]
serde = "0.8.0"
error-chain = "0.2.2"

[build-dependencies]
tango = "0.5.0"

[lib]
name = "lazers_traits"
