[package]
name = "lazers-traits"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

build = "tango-build.rs"

[dependencies]
serde = "0.9.0"
error-chain = "0.8.1"
futures = "0.1.10"

[build-dependencies]
tango = "0.5.0"

[lib]
name = "lazers_traits"
path = "src/lib.rs"
